# Generated by Django 4.0.1 on 2022-04-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_likes_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datetime_posted',
            field=models.DateTimeField(default='2022-04-15 16:04:22.871543'),
        ),
    ]
