# Generated by Django 4.0.1 on 2022-04-15 16:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_datetime_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 20, 8, 7, 127325, tzinfo=utc)),
        ),
    ]
