# Generated by Django 4.0.1 on 2022-04-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_datetime_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
