# Generated by Django 3.2.15 on 2022-10-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20221009_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_amount',
            field=models.IntegerField(default=0),
        ),
    ]
