# Generated by Django 3.2.15 on 2022-10-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20221010_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='post',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='subcommentlike',
            old_name='post',
            new_name='subcomment',
        ),
    ]
