# Generated by Django 4.2 on 2023-09-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20221011_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='memer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='memer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='memer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='memer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='save',
            old_name='memer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subcomment',
            old_name='memer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subcommentlike',
            old_name='memer',
            new_name='user',
        ),
    ]
