# Generated by Django 4.2 on 2023-10-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_post_comments_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='meme_file',
            new_name='post_file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='post_body',
            field=models.CharField(default='', max_length=256),
        ),
    ]
