# Generated by Django 4.0.1 on 2022-04-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
