# Generated by Django 4.0.1 on 2022-04-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_followers_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='following_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
