# Generated by Django 4.0.5 on 2022-06-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_following_user_following_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='chats_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
